/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { SecurityVerificationService } from "../securityVerification.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { SecurityVerificationCreateInput } from "./SecurityVerificationCreateInput";
import { SecurityVerification } from "./SecurityVerification";
import { SecurityVerificationFindManyArgs } from "./SecurityVerificationFindManyArgs";
import { SecurityVerificationWhereUniqueInput } from "./SecurityVerificationWhereUniqueInput";
import { SecurityVerificationUpdateInput } from "./SecurityVerificationUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class SecurityVerificationControllerBase {
  constructor(
    protected readonly service: SecurityVerificationService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: SecurityVerification })
  @nestAccessControl.UseRoles({
    resource: "SecurityVerification",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createSecurityVerification(
    @common.Body() data: SecurityVerificationCreateInput
  ): Promise<SecurityVerification> {
    return await this.service.createSecurityVerification({
      data: data,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        isVerified: true,
        verificationDate: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [SecurityVerification] })
  @ApiNestedQuery(SecurityVerificationFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "SecurityVerification",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async securityVerifications(
    @common.Req() request: Request
  ): Promise<SecurityVerification[]> {
    const args = plainToClass(SecurityVerificationFindManyArgs, request.query);
    return this.service.securityVerifications({
      ...args,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        isVerified: true,
        verificationDate: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: SecurityVerification })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "SecurityVerification",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async securityVerification(
    @common.Param() params: SecurityVerificationWhereUniqueInput
  ): Promise<SecurityVerification | null> {
    const result = await this.service.securityVerification({
      where: params,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        isVerified: true,
        verificationDate: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: SecurityVerification })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "SecurityVerification",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateSecurityVerification(
    @common.Param() params: SecurityVerificationWhereUniqueInput,
    @common.Body() data: SecurityVerificationUpdateInput
  ): Promise<SecurityVerification | null> {
    try {
      return await this.service.updateSecurityVerification({
        where: params,
        data: data,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          isVerified: true,
          verificationDate: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: SecurityVerification })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "SecurityVerification",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteSecurityVerification(
    @common.Param() params: SecurityVerificationWhereUniqueInput
  ): Promise<SecurityVerification | null> {
    try {
      return await this.service.deleteSecurityVerification({
        where: params,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          isVerified: true,
          verificationDate: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
